/**商品表*/
CREATE TABLE `tb_goods` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `goods_id` int(11) DEFAULT NULL COMMENT '商品的id',
  `supplier_account` int(11) unsigned DEFAULT NULL COMMENT '供应商账户',
  `goods_name` int(11) DEFAULT NULL COMMENT '商品名字',
  `category_first_id` int(11) DEFAULT NULL COMMENT '第一类目名称',
  `category_second_id` int(11) DEFAULT NULL COMMENT '第二类目名称',
  `supplier_price` double(9,2) DEFAULT NULL COMMENT '供应商报价',
  `activity_ids` varchar(20) DEFAULT NULL COMMENT '活动id列表',
  `goods_status` int(11) DEFAULT NULL COMMENT '商品状态',
  `tourist_price` double(9,2) DEFAULT NULL COMMENT '游客价格',
  `eatery_price` double(9,2) DEFAULT NULL COMMENT '食堂的价格',
  `restaurant_price` double(9,2) DEFAULT NULL COMMENT '中小餐饮的价格',
  `fresh_supermarket_price` double(9,2) DEFAULT NULL COMMENT '生鲜超市价格',
  `hotel_price` double(9,2) DEFAULT NULL COMMENT '食堂的价格',
  `unit` varchar(10) DEFAULT NULL COMMENT '单位',
  `image_urls` varchar(200) DEFAULT NULL COMMENT '图片列表，以;隔开',
  `image_head_url` varchar(20) DEFAULT NULL COMMENT '第一张图片',
  `goods_spec` varchar(20) DEFAULT NULL COMMENT '商品规格',
  `goods_desc` varchar(100) DEFAULT NULL COMMENT '商品描述',
  `goods_title` varchar(20) DEFAULT NULL COMMENT '商品标题',
  `goods_text` varchar(20) DEFAULT NULL COMMENT '商品缩略内容',
  `is_weight` int(11) DEFAULT NULL COMMENT '是否需要称重 1=是， 0=否',
  `point_rate` int(3) DEFAULT NULL COMMENT '返回积分的比例',
  `is_helper_farmer` int(3) DEFAULT NULL COMMENT '是否是助农商品 1=是， 0=否',
  `new_product` int(3) DEFAULT NULL COMMENT '是否为新品',
  `page_recommendation` int(3) DEFAULT NULL COMMENT '是否首页推荐',
  `today_recommendation` int(3) DEFAULT NULL COMMENT '是否是今日推荐',
  `freight_free` int(3) DEFAULT NULL COMMENT '是否免运费',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品表';